#!/usr/bin/env bash
# Generate a Devnet fee-payer keypair under roster-data (chmod 600), airdrop SOL,
# and write solana-devnet.env for roster-api. Never prints the secret.
set -euo pipefail

DATA_DIR="${ROSTER_DATA_DIR:-/home/ats-server/albesa/roster-data}"
mkdir -p "$DATA_DIR"
chmod 700 "$DATA_DIR"

KEY_FILE="$DATA_DIR/solana-devnet-fee-payer.json"
ENV_FILE="$DATA_DIR/solana-devnet.env"
RPC="${SOLANA_RPC_URL:-https://api.devnet.solana.com}"

if [ ! -f "$KEY_FILE" ]; then
  echo "== generating fee-payer keypair at $KEY_FILE =="
  KEY_FILE="$KEY_FILE" node --input-type=module <<'NODE'
import { Keypair } from "@solana/web3.js";
import { writeFileSync, chmodSync } from "node:fs";
const kp = Keypair.generate();
const path = process.env.KEY_FILE;
if (!path) throw new Error("KEY_FILE unset");
writeFileSync(path, JSON.stringify(Array.from(kp.secretKey)));
chmodSync(path, 0o600);
console.log("pubkey", kp.publicKey.toBase58());
NODE
else
  echo "== reusing existing fee-payer keypair =="
  KEY_FILE="$KEY_FILE" node --input-type=module <<'NODE'
import { Keypair } from "@solana/web3.js";
import { readFileSync } from "node:fs";
const secret = JSON.parse(readFileSync(process.env.KEY_FILE, "utf8"));
const kp = Keypair.fromSecretKey(Uint8Array.from(secret));
console.log("pubkey", kp.publicKey.toBase58());
NODE
fi

export KEY_FILE
PUBKEY=$(KEY_FILE="$KEY_FILE" node --input-type=module <<'NODE'
import { Keypair } from "@solana/web3.js";
import { readFileSync } from "node:fs";
const secret = JSON.parse(readFileSync(process.env.KEY_FILE, "utf8"));
process.stdout.write(Keypair.fromSecretKey(Uint8Array.from(secret)).publicKey.toBase58());
NODE
)
echo "fee-payer pubkey: $PUBKEY"

echo "== airdrop (best-effort) =="
AIRDROP_OK=0
for attempt in 1 2 3; do
  if curl -sS "$RPC" -H 'content-type: application/json' \
    -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"requestAirdrop\",\"params\":[\"$PUBKEY\",2000000000]}" \
    | grep -q '"result"'; then
    AIRDROP_OK=1
    echo "airdrop requested (attempt $attempt)"
    sleep 2
    break
  fi
  echo "airdrop attempt $attempt failed (rate limit?); retrying…"
  sleep 3
done
if [ "$AIRDROP_OK" -ne 1 ]; then
  echo "WARN: Devnet airdrop unavailable. Fund $PUBKEY manually via https://faucet.solana.com (devnet)."
  echo "      Mock rail stays the default; solana-devnet will soft-fail until the fee-payer has SOL."
fi

umask 077
cat > "$ENV_FILE" <<ENV
# Generated by scripts/setup-solana-devnet.sh — never commit.
ROSTER_WALLET=solana-devnet
ROSTER_RAIL=solana-devnet
ROSTER_SOLANA_CLUSTER=devnet
ROSTER_FEE_PAYER_KEYPAIR=$KEY_FILE
ROSTER_FEE_PAYER_PUBKEY=$PUBKEY
SOLANA_RPC_URL=$RPC
ROSTER_SOLANA_MINT_STATE=$DATA_DIR/solana-devnet-mint.json
ENV
chmod 600 "$ENV_FILE"
echo "wrote $ENV_FILE (chmod 600)"
echo "To enable on deploy: source $ENV_FILE before scripts/deploy-roster-api.sh"
echo "Explorer: https://explorer.solana.com/address/${PUBKEY}?cluster=devnet"
